### ISSUE TITLE
 Subsequent variable declarations must have the same type

### ISSUE THREAD

**Issue by fdogan0** [surveyjs/survey-analytics#298] opened 2022-12-26 06:34 UTC
Angular.json
```
{
    "name": "Test",
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "watch": "ng build --watch --configuration development",
        "test": "ng test"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^15.0.0",
        "@angular/cdk": "^13.3.9",
        "@angular/common": "^15.0.0",
        "@angular/compiler": "^15.0.0",
        "@angular/core": "^15.0.0",
        "@angular/forms": "^15.0.0",
        "@angular/platform-browser": "^15.0.0",
        "@angular/platform-browser-dynamic": "^15.0.0",
        "@angular/router": "^15.0.0",
        "@types/plotly.js-dist-min": "^2.3.1",
        "plotly.js": "^2.17.0",
        "rxjs": "~7.5.0",
        "survey-analytics": "^1.9.65",
        "survey-angular": "^1.9.65",
        "survey-creator-angular": "^1.9.65",
        "survey-creator-core": "^1.9.65",
        "tslib": "^2.3.0",
        "zone.js": "~0.12.0"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^15.0.4",
        "@angular/cli": "~15.0.4",
        "@angular/compiler-cli": "^15.0.0",
        "@types/jasmine": "~4.3.0",
        "jasmine-core": "~4.5.0",
        "karma": "~6.4.0",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage": "~2.2.0",
        "karma-jasmine": "~5.1.0",
        "karma-jasmine-html-reporter": "~2.0.0",
        "typescript": "~4.8.2"
    }
}

```
Ts.config.json

```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "outDir": "./dist/vip",
        "forceConsistentCasingInFileNames": true,
        "strict": false,
        "noImplicitOverride": true,
        "noPropertyAccessFromIndexSignature": false,
        "noImplicitReturns": false,
        "noImplicitAny": false,
        "noFallthroughCasesInSwitch": true,
        "sourceMap": true,
        "declaration": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "importHelpers": true,
        "target": "ES2022",
        "module": "ES2022",
        "useDefineForClassFields": false,
        "paths": {
            "plotly.js": [
                "../node_modules/plotly.js/lib/core.js"
            ]
        },
        "lib": [
            "ES2022",
            "dom"
        ]
    },
    "angularCompilerOptions": {
        "allowSyntheticDefaultImports": true,
        "enableI18nLegacyMessageIdFormat": false,
        "strictInjectionParameters": true,
        "strictInputAccessModifiers": true,
        "strictTemplates": true
    }
}

```
```
Error: node_modules/survey-analytics/survey.analytics.d.ts:2:16 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'englishStrings' must be of type '{ pagePrevText: string; pageNextText: string; completeText: string; previewText: string; editText: string; startSurveyText: string; otherItemText: string; noneItemText: string; selectAllItemText: string; ... 75 more ...; more: string; }', but here has type '{ groupButton: string; ungroupButton: string; selectButton: string; hideColumn: string; showColumn: string; makePrivateColumn: string; makePublicColumn: string; moveToDetail: string; showAsColumn: string; ... 58 more ...; responses: string; }'.

2     export var englishStrings: {
                 ~~~~~~~~~~~~~~

  node_modules/survey-core/survey.core.d.ts:252:16
    252     export var englishStrings: {
                       ~~~~~~~~~~~~~~
    'englishStrings' was also declared here.
```

When run `ng s` I'm getting this error. How to fix?

**Comment by JaneSjs** [comment] 2022-12-26 17:40
Hello,
I cannot seem to reproduce the issue: please check [this example](https://codesandbox.io/s/surveyjs-dashboard-angular-forked-7g512n?file=/package.json). Could you please update it to demonstrate the problematic behavior?

I look forward to your reply.

**Comment by fdogan0** [comment] 2022-12-26 20:38
I'm using `"typescript": "~4.8.2"`. I downgraded typescript version. Then I got different errors. When i check all our versions are same but i keep getting this error. What can cause this error. I used a lot of method. But didn't change.

**Comment by fdogan0** [comment] 2022-12-26 21:13
Survey.analytics.d.ts and survey.core.d.ts have same variable. The first image is analytics is [here](https://imgur.com/rt2iJgI) and the second image is survey core is [here](https://imgur.com/oQIDahE) I removed `var englishStrings` from survey.core.d.ts worked. But it is not a solution. I changed node files. Do you find a solution the this problem next time?

**Comment by JaneSjs** [comment] 2022-12-27 08:32
Hello @fdogan0,
Thank you for the clarification. We will research this issue and post updates once we have any news to share.

**Comment by tsv2013** [comment] 2022-12-27 14:49
Yes there are some modules/variables with the same names in `survey-core` and `survey-analytics` libraries. This is the ordinary situation unless you wanted to export both variables in the same module.
The live plunker example created by Jane - https://codesandbox.io/s/surveyjs-dashboard-angular-forked-7g512n?file=/package.json - worked ok because it didn't re-export anything form the `survey-core` and `survey-analytics` libraries.
Can you share a minimal reproducible example of the issue so we could reproduce it locally and to get understand what actually happens?

**Comment by itsmeneartou** [comment] 2022-12-28 13:40
Facing the same issue with one more error line:

```
Error: node_modules/survey-analytics/survey.analytics.d.ts:1723:30 - error TS2503: Cannot find namespace 'Plotly'.

1723         get chart(): Promise<Plotly.PlotlyHTMLElement>;
```

**Comment by fdogan0** [comment] 2022-12-28 14:49
Firstly install `npm i plotly.js`. Later add compilerOptions 
 ```
   "paths": {
      "plotly.js": [
        "../node_modules/plotly.js/lib/core.js"
      ]
    }
```

on tsconfig.json. I used the same code that Jane shared. Only typescript versions are different. I'm using "~4.8.2"

**Comment by itsmeneartou** [comment] 2023-01-06 20:59
Still not resolved in v1.9.67 @OlgaLarina.

**Comment by JaneSjs** [comment] 2023-01-18 08:06
Hello everyone,
We will be happy to look into this issue. For us to move forward, we need to reproduce the issue locally. 
@itsmeneartou, @fdogan0 would you please share a reproducible sample for reserarch?

We appreciate your cooperation in advance.

**Comment by fdogan0** [comment] 2023-01-19 21:01
Thank you Jane. I updated versions but didn't work I got same error. 

```
Error: node_modules/survey-analytics/survey.analytics.d.ts:2:16 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'englishStrings' must be of type '{ pagePrevText: string; pageNextText: string; completeText: string; previewText: string; editText: string; startSurveyText: string; otherItemText: string; noneItemText: string; selectAllItemText: string; ... 76 more ...; more: string; }', but here has type '{ groupButton: string; ungroupButton: string; selectButton: string; hideColumn: string; showColumn: string; makePrivateColumn: string; makePublicColumn: string; moveToDetail: string; showAsColumn: string; ... 58 more ...; responses: string; }'.

2     export var englishStrings: {
                 ~~~~~~~~~~~~~~

  node_modules/survey-core/survey.core.d.ts:256:16
    256     export var englishStrings: {
                       ~~~~~~~~~~~~~~
    'englishStrings' was also declared here.

```

**Comment by tsv2013** [comment] 2023-01-20 07:14
We need to reproduce the issue on our side. That's why @JaneSjs  earlier created an example and asked you to modify it to illustrate your case:

> I cannot seem to reproduce the issue: please check [this example](https://codesandbox.io/s/surveyjs-dashboard-angular-forked-7g512n?file=/package.json). Could you please update it to demonstrate the problematic behavior?

**Comment by JaneSjs** [comment] 2023-01-30 08:50
Please refer to the attached sample which reproduces the issue.
```
Error: node_modules/survey-analytics/survey.analytics.tabulator.d.ts:2:16 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'englishStrings' must be of type '{ pagePrevText: string; pageNextText: string; completeText: string; previewText: string; editText: string; startSurveyText: string; otherItemText: string; noneItemText: string; selectAllItemText: string; ... 76 more ...; more: string; }', but here has type '{ groupButton: string; ungroupButton: string; selectButton: string; hideColumn: string; showColumn: string; makePrivateColumn: string; makePublicColumn: string; moveToDetail: string; showAsColumn: string; ... 58 more ...; responses: string; }'.

2     export var englishStrings: {
                 ~~~~~~~~~~~~~~

  node_modules/survey-core/survey.core.d.ts:271:16
    271     export var englishStrings: {
                       ~~~~~~~~~~~~~~
    'englishStrings' was also declared here.
```

Originally posted in the following Help Desk ticket: [T11881 - Survey Analytics not working](https://surveyjs.answerdesk.io/internal/ticket/details/T11881).
[survey-analytics-poc.zip](https://github.com/surveyjs/survey-analytics/files/10533956/survey-analytics-poc.zip)

**Comment by fdogan0** [comment] 2023-01-30 09:41
Than you Jane. I downloaded and npm installed but I got same error sorry.

https://imgur.com/CQC4rlm

**Closed** 2023-01-31 08:19 UTC
Labels: bug
